name: 'Lock Threads'

on:
  schedule:
    - cron: '42 6 * * 1'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          exclude-any-issue-labels: 'keep-open'
          add-issue-labels: 'outdated'
          process-only: 'issues'
